1:
	go test -race -run TestBasic3A > t
2:
	go test -race -run TestSpeed3A > t
3:
	go test -race -run TestConcurrent3A > t
4:
	go test -race -run TestUnreliable3A > t
5:
	go test -race -run TestUnreliableOneKey3A > t
6:
	go test -race -run TestOnePartition3A > t
7:
	go test -race -run TestManyPartitionsOneClient3A > t
8:
	go test -race -run TestManyPartitionsManyClients3A > t
9:
	go test -race -run TestPersistOneClient3A > t
10:
	go test -race -run TestPersistConcurrent3A > t
11:
	go test -race -run TestPersistConcurrentUnreliable3A > t
12:
	go test -race -run TestPersistPartition3A > t
13:
	go test -race -run TestPersistPartitionUnreliable3A > t
14:
	go test -race -run TestPersistPartitionUnreliableLinearizable3A > t

