name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Show go environments
      run: go env

    - name: Test Lab2A
      run: /bin/bash -c 'cd src/raft && go env -w GO111MODULE=on && go test -race -run 2A'
      
    - name: Test Lab2B
      run: /bin/bash -c 'cd src/raft && go env -w GO111MODULE=on && go test -race -run 2B'
      
    - name: Test Lab2C
      run: /bin/bash -c 'cd src/raft && go env -w GO111MODULE=on && go test -race -run 2C'
      
    - name: Test Lab2D
      run: /bin/bash -c 'cd src/raft && go env -w GO111MODULE=on && go test -race -run 2D'
      
    - name: Test Lab3A
      run: /bin/bash -c 'cd src/raft && go env -w GO111MODULE=on && go test -race -run 3A'
