name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Show go environments
      run: go env

    - name: Test Lab2A
      run: /bin/bash -c 'cd src/main && go env -w GO111MODULE=off && go test -race -run 2A'
