name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test-Lab1-Lab2:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test Lab1
        working-directory: ./src/main
        run: bash ./test-mr.sh

      - name: Test Lab2A
        working-directory: ./src/raft
        run: go test -race -run 2A

      - name: Test Lab2B
        working-directory: ./src/raft
        run: go test -race -run 2B

      - name: Test Lab2C
        working-directory: ./src/raft
        run: go test -race -run 2C

      - name: Test Lab2D
        working-directory: ./src/raft
        run: go test -race -run 2D

  Test-Lab3:
    # Github Action's ubuntu environment can't pass TestSpeed3A due to poor cpu(2-core) while macos(3-core) can.
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test Lab3A
        working-directory: ./src/kvraft
        run: go test -race -run 3A
